config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :posts, only: %i[edit update create destroy] do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy

  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[create confirm destroy]
  before_action :correct_user, only: %i[edit update destroy]

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = 'Post updated'
      redirect_to root_url
    else
      render :edit
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render root_url
    elsif @post.save
      flash[:success] = 'post created.'
      redirect_to root_url
    else
      render 'users/index'
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted'
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :image, :image_cache)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user&.authenticate(params[:session][:password])
      log_in @user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/pass combination'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit update]
  before_action :correct_user, only: %i[edit update]

  def index
    @posts = Post.all if logged_in?
    @post = Post.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'your account has been created'
      redirect_back_or root_url
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to root_url
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def action_based
    case action_name
    when 'create'
      confirm_posts_path
    when 'edit'
      post_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user && user == current_user
  end

  # redirect to store_location or default url
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # remember where the user tried to access
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
  <div class='container'>
    <%= link_to image_tag('icons-fb-50.png', class: 'header-icon'), root_path %>
    <nav>
      <ul class='nav'>
        <li><%= link_to image_tag('icons-home-50.png', class: 'header-icon'), root_path %></li>
        <li><%= link_to image_tag('icon-people.png', class: 'header-icon'), '#' %></li>
        <% if logged_in? %>
        <li><%= link_to 'Edit profile', edit_user_path(current_user) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>FBClone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class='container'>
    <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>

</html>

app/views/posts/_post.html.erb
<li>
  <div class='content'>
    <span><%= post.user.name %> posted</span><br>
    <span><%= post.content %></span>

    <%= image_tag post.image.url if post.image && post.image.url %>

    <% if current_user?(post.user) %>
    <%= link_to 'edit', edit_post_path(post) %>
    <%= link_to 'delete', post, method: :delete, data: { confirm: 'You sure?' } %>
    <% end %>
  </div>
</li>

app/views/posts/confirm.html.erb
<% provide(:button_text, 'Are you sure?') %>
<h1 class='center-title'>Check post content</h1>

<div class='row justify-content-md-center'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_with(model: @post, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.hidden_field :content %>
    <%= @post.content %>

    <%= f.hidden_field :image_cache %>
    <%= image_tag @post.image.url if @post.image && @post.image.url %>

    <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
    <%= f.submit 'Back', class: 'btn btn-primary', name: 'back' %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class='center-title'>Edit post</h1>

<div class='row justify-content-md-center'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_with(model: @post, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.text_area :content, class: 'form-control' %>
    <%= f.file_field :image %>

    <%= f.submit 'edit post', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id='error_explanation'>
  <div class='alert alert-danger'>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true, url: confirm_posts_path) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.text_area :content, placeholder: 'input new post', class: 'form-control' %>

<%= f.file_field :image %>

<%= f.submit 'create new post', class: 'btn btn-primary' %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<% provide(:button_text, 'update profile') %>
<h1 class='center-title'>Profile update</h1>

<div class='row justify-content-md-center'>
  <div class='col-md-6 col-md-offset-3'>
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% if logged_in?  %>
logged in
<%= link_to 'Log out', logout_path, method: :delete %>
<div class='row'>
  <div class='col'>
  </div>
  <div class='col-5 content-space'>
    <section>
      <%= render 'shared/post_form' %>
    </section>
    <ol>
      <%= render @posts %>
    </ol>
  </div>
  <div class='col'>
  </div>
</div>
<% else %>
<%= render template: 'sessions/new' %>
<% end %>

app/views/users/new.html.erb
<h1 class='center-title'>Sign up</h1>

<div class='row justify-content-md-center'>
  <div class='col-md-6 col-md-offset-3'>
    <%= render 'form' %>
  </div>
</div>